image: gradle:4.8-jdk8-alpine

variables:
  # Set the location of the dependency cache to a local directory, so that it
  # can be cached between GitLab Continous Integration Jobs.
  GRADLE_USER_HOME: '.gradle'

cache:
  paths:
    # Cache the downloaded dependencies and plugins between builds.
    - '$GRADLE_USER_HOME'

build:
  script:
    - gradle build
    - gradle test jacocoTestCoverageVerification
    - gradle uploadArchives
    - 'gradle sonarqube -Dsonar.host.url=https://sonarqube.ow2.org'
